### ISSUE TITLE
Release build not setting pkgmk.conf and prt-get.conf file properly

### ISSUE THREAD

**Issue by pitill0** [crux-arm/crux-arm-release#1]
We are facing an issue when building the final release rootfs. The process is always setting up generic files instead of optimized ones.

This patch is intended to copy specific config files (pkgmk.conf and prt-get.conf) for optimized devices to the corresponding path according to the optimization chosen:

```
$ diff -uN Makefile.orig Makefile
--- Makefile.orig       2022-10-30 00:03:18.774386901 +0200
+++ Makefile    2022-10-30 00:03:12.122385746 +0200
@@ -344,12 +344,26 @@
 $(RELEASE_TAR_FILE): $(ROOTFS_STAGE1_DIR)
        @echo "[`date +'%F %T'`] Cleaning up"
        @test ! -d $(ROOTFS_STAGE1_DIR)/workspace || sudo rmdir $(ROOTFS_STAGE1_DIR)/workspace
-       @sudo rm -f $(ROOTFS_STAGE1_DIR)/etc/pkgmk.conf && \
-               sudo cp $(PORTS_DIR)/core-arm/pkgutils/pkgmk.conf $(ROOTFS_STAGE1_DIR)/etc/pkgmk.conf
-       @sudo rm -f $(ROOTFS_STAGE1_DIR)/etc/prt-get.conf && \
-               sudo cp $(PORTS_DIR)/core-arm/prt-get/prt-get.conf $(ROOTFS_STAGE1_DIR)/etc/prt-get.conf
+ifeq ($(DEVICE_OPTIMIZATION),arm)
+       @sudo cp -v $(PORTS_DIR)/core-$(DEVICE_OPTIMIZATION)/pkgutils/pkgmk.conf $(ROOTFS_STAGE1_DIR)/etc/ || true && \
+               sudo cp -v $(PORTS_DIR)/core-$(DEVICE_OPTIMIZATION)/prt-get/prt-get.conf $(ROOTFS_STAGE1_DIR)/etc/ || true
+else ifeq ($(DEVICE_OPTIMIZATION),arm64)
+       @sudo cp -v $(PORTS_DIR)/core-$(DEVICE_OPTIMIZATION)/pkgutils/pkgmk.conf $(ROOTFS_STAGE1_DIR)/etc/ || true  && \
+               sudo cp -v $(PORTS_DIR)/core-$(DEVICE_OPTIMIZATION)/prt-get/prt-get.conf $(ROOTFS_STAGE1_DIR)/ || true
+else
+       @if [ -e "$(PORTS_DIR)/$(DEVICE_OPTIMIZATION)-arm/pkgutils/pkgmk.conf" ]; then \
+               sudo cp -v $(PORTS_DIR)/$(DEVICE_OPTIMIZATION)-arm/pkgutils/pkgmk.conf $(ROOTFS_STAGE1_DIR)/etc/ ;\
+       else \
+               sudo cp -v $(PORTS_DIR)/$(DEVICE_OPTIMIZATION)-arm64/pkgutils/pkgmk.conf $(ROOTFS_STAGE1_DIR)/etc/ ;\
+       fi
+       @if [ -e "$(PORTS_DIR)/$(DEVICE_OPTIMIZATION)-arm/prt-get/prt-get.conf" ]; then \
+               sudo cp -v $(PORTS_DIR)/$(DEVICE_OPTIMIZATION)-arm/prt-get/prt-get.conf $(ROOTFS_STAGE1_DIR)/etc/ ;\
+       else \
+               sudo cp -v $(PORTS_DIR)/$(DEVICE_OPTIMIZATION)-arm64/prt-get/prt-get.conf $(ROOTFS_STAGE1_DIR)/etc/ ;\
+       fi
+endif
        @echo "[`date +'%F %T'`] Building $(RELEASE_TAR_FILE)"
        @cd $(ROOTFS_STAGE1_DIR) && \
-               sudo tar cJf $(RELEASE_TAR_FILE) * && \
+               sudo tar cJf ../$(RELEASE_TAR_FILE) * && \
                sudo chown $(CURRENT_UID):$(CURRENT_GID) $(RELEASE_TAR_FILE)
-       @echo "[`date +'%F %T'`] Release completed"
+       @echo "[`date +'%F %T'`] Release completed"
```

**Comment by pitill0** [comment]
Not working.
core-arm|core-arm64
and for optimizations should be odroidxu4-arm and raspberrypi3-arm64 (not core-$DEVICE_OPTIMIZATION)

**Comment by pitill0** [comment]
diff --git a/Makefile b/Makefile
index f297189..81a41e9 100644
--- a/Makefile
+++ b/Makefile
@@ -333,9 +333,17 @@ $(RELEASE_TAR_FILE): $(ROOTFS_STAGE1_DIR)
        @test ! -d $(ROOTFS_STAGE1_DIR)/workspace || \
                sudo rmdir $(ROOTFS_STAGE1_DIR)/workspace
        @sudo rm -f $(ROOTFS_STAGE1_DIR)/etc/pkgmk.conf && \
-               sudo cp $(PORTS_DIR)/core-arm/pkgutils/pkgmk.conf $(ROOTFS_STAGE1_DIR)/etc/pkgmk.conf
+               if $(DEVICE_OPTIMIZATION) == (arm|arm64) then
+                       sudo cp $(PORTS_DIR)/core-$(DEVICE_OPTIMIZATION)/pkgutils/pkgmk.conf $(ROOTFS_STAGE1_DIR)/etc/pkgmk.conf
+               else
+                       sudo cp $(PORTS_DIR)/$(DEVICE_OPTIMIZATION)/pkgutils/pkgmk.conf $(ROOTFS_STAGE1_DIR)/etc/pkgmk.conf
+               fi
        @sudo rm -f $(ROOTFS_STAGE1_DIR)/etc/prt-get.conf && \
-               sudo cp $(PORTS_DIR)/core-arm/prt-get/prt-get.conf $(ROOTFS_STAGE1_DIR)/etc/prt-get.conf
+               if $(DEVICE_OPTIMIZATION) == (arm|arm64) then
+                       sudo cp $(PORTS_DIR)/core-$(DEVICE_OPTIMIZATION)/prt-get/prt-get.conf $(ROOTFS_STAGE1_DIR)/etc/prt-get.conf
+               else
+                       sudo cp $(PORTS_DIR)/$(DEVICE_OPTIMIZATION)/prt-get/prt-get.conf $(ROOTFS_STAGE1_DIR)/etc/prt-get.conf
+               fi
        @echo "[`date +'%F %T'`] Building $(RELEASE_TAR_FILE)"
        @cd $(ROOTFS_STAGE1_DIR) && \
                sudo tar cJf $(RELEASE_TAR_FILE) * && \

**Comment by pitill0** [comment]
ifeq ($(DEVICE_OPTIMIZATION),$(filter $(DEVICE_OPTIMIZATION),arm arm64)
	sudo cp $(PORTS_DIR)/core-$(DEVICE_OPTIMIZATION)/pkgutils/pkgmk.conf $(ROOTFS_STAGE1_DIR)/etc/pkgmk.conf
	sudo cp $(PORTS_DIR)/core-arm/prt-get/prt-get.conf $(ROOTFS_STAGE1_DIR)/etc/prt-get.conf
else
	sudo cp $(PORTS_DIR)/$(DEVICE_OPTIMIZATION)/prt-get/prt-get.conf $(ROOTFS_STAGE1_DIR)/etc/prt-get.conf
	sudo cp $(PORTS_DIR)/$(DEVICE_OPTIMIZATION)/prt-get/prt-get.conf $(ROOTFS_STAGE1_DIR)/etc/prt-get.conf
endinf

**Comment by sepen** [comment]
LGTM but why you use `../$(RELEASE_TAR_FILE)`. The RELEASE_TAR_FILE should be an absolute path so there is no need to use `../`

**Comment by sepen** [comment]
I think we can do it in a simpler way. We can get the first value of the COLLECTIONS list variable.

```
--- a/Makefile
+++ b/Makefile
@@ -344,10 +344,11 @@ release: $(RELEASE_TAR_FILE)
 $(RELEASE_TAR_FILE): $(ROOTFS_STAGE1_DIR)
        @echo "[`date +'%F %T'`] Cleaning up"
        @test ! -d $(ROOTFS_STAGE1_DIR)/workspace || sudo rmdir $(ROOTFS_STAGE1_DIR)/workspace
-       @sudo rm -f $(ROOTFS_STAGE1_DIR)/etc/pkgmk.conf && \
-               sudo cp $(PORTS_DIR)/core-arm/pkgutils/pkgmk.conf $(ROOTFS_STAGE1_DIR)/etc/pkgmk.conf
-       @sudo rm -f $(ROOTFS_STAGE1_DIR)/etc/prt-get.conf && \
-               sudo cp $(PORTS_DIR)/core-arm/prt-get/prt-get.conf $(ROOTFS_STAGE1_DIR)/etc/prt-get.conf
+       @sudo rm -f $(ROOTFS_STAGE1_DIR)/etc/pkgmk.conf
+       @sudo rm -f $(ROOTFS_STAGE1_DIR)/etc/prt-get.conf
+       @echo "[`date +'%F %T'`] Copying config files"
+       @sudo cp $(PORTS_DIR)/$(word 1, $(COLLECTIONS))/pkgutils/pkgmk.conf $(ROOTFS_STAGE1_DIR)/etc/pkgmk.conf
+       @sudo cp $(PORTS_DIR)/$(word 1, $(COLLECTIONS))/prt-get/prt-get.conf $(ROOTFS_STAGE1_DIR)/etc/prt-get.conf
        @echo "[`date +'%F %T'`] Building $(RELEASE_TAR_FILE)"
        @cd $(ROOTFS_STAGE1_DIR) && \
                sudo tar cJf $(RELEASE_TAR_FILE) * && \
```

**Comment by pitill0** [comment]
It serms to be a cleaner and a simpler way to manager this issue.

I'll test this patch locally and I'll share results.

**Comment by pitill0** [comment]
It seems to be working right.
This issue can be closed.
