### ISSUE TITLE
Release 3.7 samsung-chromebook

### ISSUE THREAD

**Issue by sepen** [crux-arm/crux-arm-release#10]

**Comment by pitill0** [comment]
RC1 ready for testing:

+ CFLAGS="-O2 -pipe -mfloat-abi=hard -march=armv7ve -mtune=cortex-a15 -mfpu=neon"

Download for testing and report issues:

+ https://sourceforge.net/projects/crux-arm/files/releases/3.7/crux-arm-3.7-RC1-samsung-chromebook.rootfs.tar.xz/download

**Comment by pitill0** [comment]
Won't be implemented. Blocked due to old kernel with current glibc (toolchain). It's possible to downgrade and test, but not now.
