### ISSUE TITLE
Restore prt-get.conf information after exiting chroot on stage1

### ISSUE THREAD

**Issue by pitill0** [crux-arm/crux-arm-release#4]
We'll try to put the right information again on prt-get.conf file after exiting from chroot on stage1.
This way allow us to enter again stage1 without running again make prepare-prtgetconf which points to /workspace/ports instead of ports/

```
diff --git a/Makefile b/Makefile
index 315fb50..d065d91 100644
--- a/Makefile
+++ b/Makefile
@@ -317,6 +317,7 @@ stage1:
        @sudo umount -f $(ROOTFS_STAGE1_DIR)/proc
        @echo "[`date +'%F %T'`] Unmounting $(ROOTFS_STAGE1_DIR)/dev"
        @sudo umount -f $(ROOTFS_STAGE1_DIR)/dev
+       @sed "s|/workspace/||g" -i $(WORKSPACE_DIR)/prt-get.conf

 #------------------------------------------------------------------------------
 # BOOSTRAP
```

**Comment by sepen** [comment]
With your patch a prt-get.conf line like
`prtdir /workspace/ports/foo` would be converted to `prtdir ports/foo` which would be a relative path. I have never tried using relative paths in prt-get.conf. I guess in this sense it would be better to use something like:
```
diff --git a/Makefile b/Makefile
index 315fb50..d065d91 100644
--- a/Makefile
+++ b/Makefile
@@ -317,6 +317,7 @@ stage1:
        @sudo umount -f $(ROOTFS_STAGE1_DIR)/proc
        @echo "[`date +'%F %T'`] Unmounting $(ROOTFS_STAGE1_DIR)/dev"
        @sudo umount -f $(ROOTFS_STAGE1_DIR)/dev
+       @sed "s|$(WORKSPACE_DIR)||g" -i $(WORKSPACE_DIR)/prt-get.conf

 #------------------------------------------------------------------------------
 # BOOSTRAP
```
Anyway, I don't quite understand what situation this patch solves. Could you provide more info about how to reproduce the error?

On the other hand, something to note is that if the prt-get.conf file is modified, as it is a dependency of targets in the Makefile, these will be remade unnecessarily, when detecting that objective is newer than its target.

**Comment by pitill0** [comment]
On stage1 build error, you can see that prt-get.conf file still points to /workspace/prt-get.conf so when trying to do again stage1, we can't get the right ports collections path and the build breaks.

Regarding remaking unnecessary targets, it must be solved by hand with a touch on rootfs-stage1 (with or without modifying prt-get.conf, this should be done to continue on stage1 build at the same point and don't rebuild all)

**Comment by sepen** [comment]
I think that all this has an underlying problem and I think that it could be solved if we did not reuse the prt-get.conf file for both stages.
How about if we had separate prt-get.conf targets, something like `prepare-stage0-prtgetconf` and `prepare-stage1-prtgetconf`. This way we would also avoid the parts that do `clean-prtgetconf` as a hack in the Makefile.

**Comment by sepen** [comment]
@pitill0 I think the problem was solved from here https://github.com/crux-arm/crux-arm-release/commit/ee444ca3868a71580722290f08cf6eb68ce1fb8c

Is the problem still happening to you?

**Comment by pitill0** [comment]
It seems to be fixed after the last change. I'll close this issue.
