### ISSUE TITLE
Release 3.7 aarch64 raspberrypi3

### ISSUE THREAD

**Issue by sepen** [crux-arm/crux-arm-release#8]

**Comment by pitill0** [comment]
RC1 ready for testing:
+ export CFLAGS="-O2 -pipe -march=armv8-a+crc -mabi=lp64 -mlittle-endian"

Download for testing and report issues:
+ https://sourceforge.net/projects/crux-arm/files/releases/3.7/crux-arm-3.7-aarch64-RC1-raspberrypi3.rootfs.tar.xz/download

**Comment by pitill0** [comment]
RC1 ready to be deployed as final release
